import { generatePageMetadata } from '@/lib/metadata'
import { KnowledgePage, type KnowledgeArticle } from '@/app/lumora-premium/_components/KnowledgePage'
import { resolveStorefrontLocale, type StorefrontLocale } from '@/app/lumora-premium/_components/storefront-localization'

export function generateStaticParams() {
  return [{ locale: 'nl' }, { locale: 'en' }, { locale: 'de' }]
}

const meta = {
  nl: { title: 'Steenwol Stekpluggen Gebruiken | Paper Plug Trays', description: 'Wat zijn Paper Plug Trays, hoe werkt de Ellepot FP 12+ papierwikkel, waarom is de wikkel biologisch afbreekbaar en hoe voorkom je transplantatieschok en optimaliseer je de wortelvorming.', keywords: ['paper plug trays', 'wat zijn paper plug trays', 'ellepot fp 12+', 'biologisch afbreekbaar', 'transplantatieschok voorkomen', 'wortelvorming'] },
  en: { title: 'Paper Plug Trays explained: FP 12+, biodegradability, transplant shock and rooting', description: 'What Paper Plug Trays are, how the Ellepot FP 12+ paper sleeve works, why the sleeve is biodegradable and how to prevent transplant shock and optimise root formation.', keywords: ['paper plug trays', 'what are paper plug trays', 'ellepot fp 12+', 'biodegradable', 'prevent transplant shock', 'root formation'] },
  de: { title: 'Paper Plug Trays erklärt: FP 12+, Abbaubarkeit, Transplantationsschock und Bewurzelung', description: 'Was Paper Plug Trays sind, wie die Ellepot FP 12+ Papierhülle funktioniert, warum die Hülle biologisch abbaubar ist und wie Sie Transplantationsschock vermeiden und die Wurzelbildung optimieren.', keywords: ['paper plug trays', 'was sind paper plug trays', 'ellepot fp 12+', 'biologisch abbaubar', 'transplantationsschock vermeiden', 'wurzelbildung'] },
}

export async function generateMetadata(props: { params: Promise<{ locale: string }> }) {
  const locale = resolveStorefrontLocale((await props.params).locale)
  return generatePageMetadata({ ...meta[locale], locale, path: '/paper-plug-trays-uitgelegd', availableLocales: ['nl', 'en', 'de'] })
}

const article: Record<StorefrontLocale, KnowledgeArticle> = {
  nl: {
    tag: 'Kennisbank',
    title: 'Steenwol stekpluggen gebruiken: van tray tot uitplanten',
    intro: 'Alles over stekpluggen van steenwol met een papierwikkel: wat het is, hoe de Ellepot FP 12+ technologie werkt en hoe je er de beste beworteling mee haalt.',
    answer: { title: 'In het kort', text: 'Een Paper Plug Tray is een kweektray met steenwol pluggen die elk in een papieren wikkel zitten. De wikkel houdt de plug bij elkaar, laat wortels erdoorheen groeien en kan met plug en al de grond in. Geen plastic potje, geen transplantatieschok.' },
    sections: [
      { kind: 'facts', title: 'Twee tray-indelingen', intro: 'Beide uitvoeringen worden per complete doos geleverd.', facts: [{ value: '84', label: 'cellen · Ø38 × 42 mm · 8 trays per doos' }, { value: '104', label: 'cellen · Ø32 × 40 mm · 7 trays per doos' }, { value: '672', label: 'cellen per doos (tray 84)' }, { value: '728', label: 'cellen per doos (tray 104)' }] },
      { kind: 'cards', title: 'Wat is Ellepot FP 12+?', intro: 'FP 12+ is het papier van Ellepot dat om elke plug zit.', items: [{ title: 'Meer dan 12 maanden stabiel', text: 'Het papier behoudt zijn structuur tijdens een lange opkweek, ook bij vochtige omstandigheden.' }, { title: 'Doorwortelbaar', text: 'Wortels groeien door het papier heen en worden aan de buitenkant door lucht gesnoeid. Dat geeft een compacte, vertakte wortelkluit.' }, { title: 'Biologisch afbreekbaar', text: 'Het papier is gemaakt van houtvezels en breekt in de grond af. Er blijft geen plastic achter.' }] },
      { kind: 'list', title: 'Waarom de wikkel biologisch afbreekbaar is', intro: 'De papierwikkel vervangt het plastic potje of de losse plug.', items: ['Gemaakt van hernieuwbare houtvezels', 'Breekt af nadat de plug is uitgeplant', 'Geen plastic afval in de kwekerij', 'Geen losse pluggen die uit elkaar vallen', 'De steenwol zelf blijft; alleen de wikkel is afbreekbaar'] },
      { kind: 'steps', title: 'Transplantatieschok voorkomen', intro: 'Transplantatieschok ontstaat als wortels beschadigen of uitdrogen bij het verplanten. Met een papierwikkel voorkom je het grootste deel daarvan.', items: ['Plant de complete plug uit, inclusief de papierwikkel. Verwijder de wikkel niet.', 'Verplant op tijd: zodra witte wortelpunten door het papier zichtbaar zijn.', 'Geef de plug een dag voor het verplanten goed water, zodat de kluit vochtig is.', 'Plant op dezelfde diepte als in de tray; zet de plug niet dieper.', 'Zorg voor goed contact tussen plug en substraat en geef direct water.', 'Houd de eerste dagen de luchtvochtigheid hoog en vermijd fel direct zonlicht.', 'Begin pas met voeding zodra je nieuwe groei ziet.'] },
      { kind: 'steps', title: 'Wortelvorming optimaliseren', intro: 'Een gezonde wortelkluit begint in de tray.', items: ['Maak de pluggen vóór het stekken of zaaien goed nat en laat ze uitlekken.', 'Houd de steenwol vochtig maar niet verzadigd; te nat betekent te weinig zuurstof.', 'Houd een worteltemperatuur van 18 tot 24 °C aan.', 'Zorg voor een luchtvochtigheid van ongeveer 80 tot 90 procent bij stekken, en ventileer dagelijks.', 'Werk met een lage EC in de eerste week en bouw langzaam op.', 'Controleer na 10 tot 14 dagen op wortels door het papier; dan is de plug klaar om te verplanten.'] },
      { kind: 'list', title: 'Waar Paper Plug Trays worden gebruikt', items: ['Groenteplanten zoals tomaat, paprika en komkommer', 'Sierplanten en vaste planten', 'Kruiden en microgreens', 'Stekken van houtige gewassen', 'Vertical farming en hydrocultuur'] },
    ],
    cta: { title: 'Kies je Paper Plug Tray', text: 'Tray 84 voor een grotere plug, tray 104 voor meer planten per tray. Per complete doos, gratis verzending binnen Nederland, België en Duitsland.', button: 'Bekijk de Paper Plug Trays' },
    faq: [{ question: 'Wat is een Paper Plug Tray?', answer: 'Een kweektray met steenwol pluggen die elk in een Ellepot FP 12+ papierwikkel zitten. De plug wordt met wikkel en al uitgeplant.' }, { question: 'Moet je de papierwikkel verwijderen bij het uitplanten?', answer: 'Nee. Plant de complete plug uit. Wortels groeien door het papier heen en het papier breekt in de grond af.' }, { question: 'Hoe voorkom je transplantatieschok?', answer: 'Plant de complete plug op tijd en op dezelfde diepte uit, houd de kluit vochtig, geef direct water en houd de eerste dagen de luchtvochtigheid hoog.' }],
  },
  en: {
    tag: 'Knowledge base',
    title: 'Paper Plug Trays explained',
    intro: 'Everything about rockwool plugs with a paper sleeve: what they are, how Ellepot FP 12+ technology works and how to get the best rooting with them.',
    answer: { title: 'In short', text: 'A Paper Plug Tray is a propagation tray with rockwool plugs that each sit in a paper sleeve. The sleeve holds the plug together, lets roots grow through it and goes into the ground with the plug. No plastic pot, no transplant shock.' },
    sections: [
      { kind: 'facts', title: 'Two tray layouts', intro: 'Both versions are supplied by the complete box.', facts: [{ value: '84', label: 'cells · Ø38 × 42 mm · 8 trays per box' }, { value: '104', label: 'cells · Ø32 × 40 mm · 7 trays per box' }, { value: '672', label: 'cells per box (tray 84)' }, { value: '728', label: 'cells per box (tray 104)' }] },
      { kind: 'cards', title: 'What is Ellepot FP 12+?', intro: 'FP 12+ is the Ellepot paper around every plug.', items: [{ title: 'Stable for more than 12 months', text: 'The paper keeps its structure during a long propagation period, even in humid conditions.' }, { title: 'Roots grow through', text: 'Roots grow through the paper and are air-pruned on the outside. That gives a compact, branched root ball.' }, { title: 'Biodegradable', text: 'The paper is made from wood fibres and breaks down in the soil. No plastic is left behind.' }] },
      { kind: 'list', title: 'Why the sleeve is biodegradable', intro: 'The paper sleeve replaces the plastic pot or the loose plug.', items: ['Made from renewable wood fibres', 'Breaks down after the plug is planted', 'No plastic waste in the nursery', 'No loose plugs that fall apart', 'The rockwool itself remains; only the sleeve is biodegradable'] },
      { kind: 'steps', title: 'Preventing transplant shock', intro: 'Transplant shock occurs when roots are damaged or dry out during transplanting. A paper sleeve prevents most of it.', items: ['Plant the complete plug, including the paper sleeve. Do not remove the sleeve.', 'Transplant on time: as soon as white root tips are visible through the paper.', 'Water the plug well the day before transplanting so the root ball is moist.', 'Plant at the same depth as in the tray; do not set the plug deeper.', 'Ensure good contact between plug and substrate and water immediately.', 'Keep humidity high for the first days and avoid strong direct sunlight.', 'Start feeding only once you see new growth.'] },
      { kind: 'steps', title: 'Optimising root formation', intro: 'A healthy root ball starts in the tray.', items: ['Soak the plugs well before sticking or sowing and let them drain.', 'Keep the rockwool moist but not saturated; too wet means too little oxygen.', 'Keep a root temperature of 18 to 24 °C.', 'Aim for a humidity of around 80 to 90 percent for cuttings, and ventilate daily.', 'Work with a low EC in the first week and build up slowly.', 'Check for roots through the paper after 10 to 14 days; the plug is then ready to transplant.'] },
      { kind: 'list', title: 'Where Paper Plug Trays are used', items: ['Vegetable plants such as tomato, pepper and cucumber', 'Ornamentals and perennials', 'Herbs and microgreens', 'Cuttings of woody crops', 'Vertical farming and hydroponics'] },
    ],
    cta: { title: 'Choose your Paper Plug Tray', text: 'Tray 84 for a larger plug, tray 104 for more plants per tray. By the complete box, free shipping within the Netherlands, Belgium and Germany.', button: 'View the Paper Plug Trays' },
    faq: [{ question: 'What is a Paper Plug Tray?', answer: 'A propagation tray with rockwool plugs that each sit in an Ellepot FP 12+ paper sleeve. The plug is planted with the sleeve.' }, { question: 'Do you remove the paper sleeve when planting?', answer: 'No. Plant the complete plug. Roots grow through the paper and the paper breaks down in the soil.' }, { question: 'How do you prevent transplant shock?', answer: 'Plant the complete plug on time and at the same depth, keep the root ball moist, water immediately and keep humidity high for the first days.' }],
  },
  de: {
    tag: 'Wissensdatenbank',
    title: 'Paper Plug Trays erklärt',
    intro: 'Alles über Steinwollstecker mit Papierhülle: was sie sind, wie die Ellepot FP 12+ Technologie funktioniert und wie Sie damit die beste Bewurzelung erzielen.',
    answer: { title: 'Kurz gesagt', text: 'Ein Paper Plug Tray ist eine Anzuchtplatte mit Steinwollsteckern, die jeweils in einer Papierhülle sitzen. Die Hülle hält den Stecker zusammen, lässt Wurzeln hindurchwachsen und kommt mit dem Stecker in die Erde. Kein Kunststofftopf, kein Transplantationsschock.' },
    sections: [
      { kind: 'facts', title: 'Zwei Tray-Aufteilungen', intro: 'Beide Ausführungen werden im kompletten Karton geliefert.', facts: [{ value: '84', label: 'Zellen · Ø38 × 42 mm · 8 Platten pro Karton' }, { value: '104', label: 'Zellen · Ø32 × 40 mm · 7 Platten pro Karton' }, { value: '672', label: 'Zellen pro Karton (Tray 84)' }, { value: '728', label: 'Zellen pro Karton (Tray 104)' }] },
      { kind: 'cards', title: 'Was ist Ellepot FP 12+?', intro: 'FP 12+ ist das Ellepot-Papier um jeden Stecker.', items: [{ title: 'Mehr als 12 Monate stabil', text: 'Das Papier behält seine Struktur während einer langen Anzucht, auch bei feuchten Bedingungen.' }, { title: 'Durchwurzelbar', text: 'Wurzeln wachsen durch das Papier und werden außen durch Luft beschnitten. Das ergibt einen kompakten, verzweigten Wurzelballen.' }, { title: 'Biologisch abbaubar', text: 'Das Papier besteht aus Holzfasern und baut sich im Boden ab. Es bleibt kein Kunststoff zurück.' }] },
      { kind: 'list', title: 'Warum die Hülle biologisch abbaubar ist', intro: 'Die Papierhülle ersetzt den Kunststofftopf oder den losen Stecker.', items: ['Aus erneuerbaren Holzfasern hergestellt', 'Baut sich nach dem Auspflanzen ab', 'Kein Kunststoffabfall in der Gärtnerei', 'Keine losen Stecker, die auseinanderfallen', 'Die Steinwolle selbst bleibt; nur die Hülle ist abbaubar'] },
      { kind: 'steps', title: 'Transplantationsschock vermeiden', intro: 'Transplantationsschock entsteht, wenn Wurzeln beim Umpflanzen beschädigt werden oder austrocknen. Mit einer Papierhülle vermeiden Sie den größten Teil davon.', items: ['Pflanzen Sie den kompletten Stecker samt Papierhülle aus. Entfernen Sie die Hülle nicht.', 'Pflanzen Sie rechtzeitig um: sobald weiße Wurzelspitzen durch das Papier sichtbar sind.', 'Wässern Sie den Stecker am Tag vor dem Umpflanzen gut, damit der Ballen feucht ist.', 'Pflanzen Sie in derselben Tiefe wie im Tray; setzen Sie den Stecker nicht tiefer.', 'Sorgen Sie für guten Kontakt zwischen Stecker und Substrat und gießen Sie sofort.', 'Halten Sie die Luftfeuchtigkeit in den ersten Tagen hoch und vermeiden Sie starke direkte Sonne.', 'Beginnen Sie erst mit der Düngung, wenn Sie neues Wachstum sehen.'] },
      { kind: 'steps', title: 'Wurzelbildung optimieren', intro: 'Ein gesunder Wurzelballen beginnt im Tray.', items: ['Wässern Sie die Stecker vor dem Stecken oder Säen gut und lassen Sie sie abtropfen.', 'Halten Sie die Steinwolle feucht, aber nicht gesättigt; zu nass bedeutet zu wenig Sauerstoff.', 'Halten Sie eine Wurzeltemperatur von 18 bis 24 °C ein.', 'Streben Sie bei Stecklingen eine Luftfeuchtigkeit von etwa 80 bis 90 Prozent an und lüften Sie täglich.', 'Arbeiten Sie in der ersten Woche mit einem niedrigen EC-Wert und steigern Sie langsam.', 'Prüfen Sie nach 10 bis 14 Tagen auf Wurzeln durch das Papier; dann ist der Stecker bereit zum Umpflanzen.'] },
      { kind: 'list', title: 'Wo Paper Plug Trays eingesetzt werden', items: ['Gemüsepflanzen wie Tomate, Paprika und Gurke', 'Zierpflanzen und Stauden', 'Kräuter und Microgreens', 'Stecklinge von Gehölzen', 'Vertical Farming und Hydrokultur'] },
    ],
    cta: { title: 'Wählen Sie Ihr Paper Plug Tray', text: 'Tray 84 für einen größeren Stecker, Tray 104 für mehr Pflanzen pro Platte. Im kompletten Karton, kostenloser Versand in die Niederlande, nach Belgien und Deutschland.', button: 'Paper Plug Trays ansehen' },
    faq: [{ question: 'Was ist ein Paper Plug Tray?', answer: 'Eine Anzuchtplatte mit Steinwollsteckern, die jeweils in einer Ellepot FP 12+ Papierhülle sitzen. Der Stecker wird samt Hülle ausgepflanzt.' }, { question: 'Muss man die Papierhülle beim Auspflanzen entfernen?', answer: 'Nein. Pflanzen Sie den kompletten Stecker aus. Wurzeln wachsen durch das Papier, und das Papier baut sich im Boden ab.' }, { question: 'Wie vermeidet man Transplantationsschock?', answer: 'Den kompletten Stecker rechtzeitig und in derselben Tiefe auspflanzen, den Ballen feucht halten, sofort gießen und die Luftfeuchtigkeit in den ersten Tagen hoch halten.' }],
  },
}

export default async function PaperPlugTraysExplainedPage(props: { params: Promise<{ locale: string }> }) {
  const locale = resolveStorefrontLocale((await props.params).locale)
  return <KnowledgePage locale={locale} slug="paper-plug-trays-uitgelegd" article={article[locale]} />
}
