[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NPM_FLAGS = "--no-optional --legacy-peer-deps --force"
  NODE_ENV = "production"
  NEXT_PRIVATE_TARGET = "server"

# Edge Functions for middleware
[[edge_functions]]
  path = "/*"
  function = "middleware"

# Handle image files
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Domain-specific robots.txt files
[[redirects]]
  from = "/robots.txt"
  to = "/robots.nl.txt"
  status = 200
  conditions = {host = ["lumorahorticulture.nl", "www.lumorahorticulture.nl"]}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.com.txt"
  status = 200
  conditions = {host = ["lumorahorticulture.com", "www.lumorahorticulture.com"]}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.de.txt"
  status = 200
  conditions = {host = ["lumorahorticulture.de", "www.lumorahorticulture.de"]}

# Domain-specific sitemap files
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-lumorahorticulture.nl.xml"
  status = 200
  conditions = {host = ["lumorahorticulture.nl", "www.lumorahorticulture.nl"]}

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-lumorahorticulture.com.xml"
  status = 200
  conditions = {host = ["lumorahorticulture.com", "www.lumorahorticulture.com"]}

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-lumorahorticulture.de.xml"
  status = 200
  conditions = {host = ["lumorahorticulture.de", "www.lumorahorticulture.de"]}

# Functions configuration to reduce bundle size
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "@next/swc-*"]