[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NPM_FLAGS = "--no-optional --legacy-peer-deps --force"
  NODE_ENV = "production"

# Handle image files
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Domain-specific configurations

# Domain-specific robots.txt files
[[redirects]]
  from = "/robots.txt"
  to = "/robots.nl.txt"
  status = 200
  conditions = {host = ["lumorahorticulture.nl", "www.lumorahorticulture.nl"]}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.com.txt"
  status = 200
  conditions = {host = ["lumorahorticulture.com", "www.lumorahorticulture.com"]}

[[redirects]]
  from = "/robots.txt"
  to = "/robots.de.txt"
  status = 200
  conditions = {host = ["lumorahorticulture.de", "www.lumorahorticulture.de"]}

# Domain-specific sitemap files - make sure they're served from the right domain
[[redirects]]
  from = "/sitemap-lumorahorticulture.nl.xml"
  to = "/sitemap-lumorahorticulture.nl.xml"
  status = 200
  conditions = {host = ["lumorahorticulture.nl", "www.lumorahorticulture.nl"]}

[[redirects]]
  from = "/sitemap-lumorahorticulture.com.xml"
  to = "/sitemap-lumorahorticulture.com.xml"
  status = 200
  conditions = {host = ["lumorahorticulture.com", "www.lumorahorticulture.com"]}

[[redirects]]
  from = "/sitemap-lumorahorticulture.de.xml"
  to = "/sitemap-lumorahorticulture.de.xml"
  status = 200
  conditions = {host = ["lumorahorticulture.de", "www.lumorahorticulture.de"]}

# Block sitemap files from wrong domains (404 for cross-domain sitemap access)
[[redirects]]
  from = "/sitemap-lumorahorticulture.com.xml"
  to = "/index.html"
  status = 404
  force = true
  conditions = {host = ["lumorahorticulture.nl", "www.lumorahorticulture.nl"]}

[[redirects]]
  from = "/sitemap-lumorahorticulture.com.xml"
  to = "/index.html"
  status = 404
  force = true
  conditions = {host = ["lumorahorticulture.de", "www.lumorahorticulture.de"]}

[[redirects]]
  from = "/sitemap-lumorahorticulture.de.xml"
  to = "/index.html"
  status = 404
  force = true
  conditions = {host = ["lumorahorticulture.nl", "www.lumorahorticulture.nl"]}

[[redirects]]
  from = "/sitemap-lumorahorticulture.de.xml"
  to = "/index.html"
  status = 404
  force = true
  conditions = {host = ["lumorahorticulture.com", "www.lumorahorticulture.com"]}

[[redirects]]
  from = "/sitemap-lumorahorticulture.nl.xml"
  to = "/index.html"
  status = 404
  force = true
  conditions = {host = ["lumorahorticulture.com", "www.lumorahorticulture.com"]}

[[redirects]]
  from = "/sitemap-lumorahorticulture.nl.xml"
  to = "/index.html"
  status = 404
  force = true
  conditions = {host = ["lumorahorticulture.de", "www.lumorahorticulture.de"]}

# Make sure static assets are properly served first
[[redirects]]
  from = "/productAfbeeldingen/*"
  to = "/productAfbeeldingen/:splat"
  status = 200

# SPA fallback - should come after all other redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
