# Netlify CI Configuration
[build]
  # The directory to change to before starting a build
  base = "/"

  # Directory with the deploy-ready files
  publish = ".next"
  
  # Build command
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  # Set Next.js to use static export
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NPM_FLAGS = "--no-optional --legacy-peer-deps --force"
  NODE_ENV = "production"

# Use the Next.js plugin for optimal handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
