[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NPM_FLAGS = "--no-optional --legacy-peer-deps --force"
  NODE_ENV = "production"

# Handle image files
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Domain-specific configurations

# These redirects are no longer needed with domain-based localization
# as each domain serves content in its specific language

# Make sure static assets are properly served first
[[redirects]]
  from = "/productAfbeeldingen/*"
  to = "/productAfbeeldingen/:splat"
  status = 200

# SPA fallback - should come after all other redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
