import type { KnowledgeArticle } from '../_components/KnowledgePage'

const guideLink = { text: 'steenwol stekpluggen gebruiken', href: '/paper-plug-trays-uitgelegd' }
const productLink = { text: 'steenwol stekpluggen in trays van 84 of 104 cellen', href: '/stekpluggen-steenwol' }
const verspeenLink = { text: 'zaailingen verspenen', href: '/zaailingen-verspenen' }
const sources = {
  verspenen: { href: 'https://www.bolster.nl/wat-is-verspenen-en-hoe-doe-je-dat/t24892', label: 'De Bolster: wat is verspenen?', description: 'Het verschil met verpotten en het voorzichtig verplaatsen van kiemplanten.' },
  aftercare: { href: 'https://www.rhs.org.uk/get-involved/grow-with-it/pdfs/grow-with-it-support-pack.pdf', label: 'RHS: seedling aftercare (PDF)', description: 'Verzorging, verspenen en uitdunnen van zaailingen.' },
  tomatoes: { href: 'https://www.bolster.nl/tomaten-telen-onze-tips/t4957', label: 'De Bolster: tomaten telen', description: 'Nederlandse teelttips voor voorzaaien, zaaidiepte en uitplanten.' },
  rhsTomatoes: { href: 'https://www.rhs.org.uk/vegetables/tomatoes/grow-your-own', label: 'RHS: growing tomatoes', description: 'Kieming, licht en verdere opkweek; de kalender is gericht op het Britse klimaat.' },
  peppers: { href: 'https://www.bolster.nl/paprika-telen/t23042', label: 'De Bolster: paprika telen', description: 'Zaaien, standplaats en uitplanten in kas en vollegrond.' },
  rhsPeppers: { href: 'https://www.rhs.org.uk/vegetables/peppers/grow-your-own', label: 'RHS: growing sweet peppers', description: 'Warmte en opkweek van paprika; het Britse teeltadvies kan qua timing verschillen.' },
  pepperSowing: { href: 'https://www.rhs.org.uk/education-learning/children-young-people/family-activities/grow-it/peppers', label: 'RHS: paprika zaaien in potjes', description: 'Een praktische zaaimethode met afdekking van het zaad.' },
}
const cta = { title: 'Opkweken in steenwol pluggen?', text: 'Bekijk de plugmaten en doosinhoud en kies wat past bij jouw gewas en teeltsysteem.', button: 'Bekijk de Paper Plug Trays' }

export const opkweekGuides = {
  'zaailingen-verspenen': {
    title: 'Zaailingen verspenen: wanneer en hoe doe je dat?',
    intro: 'Je zaailingen staan boven de grond en beginnen ruimte te vragen. Hier lees je wanneer je losse plantjes verspeent, hoe je de wortels voorzichtig behandelt en wat anders werkt bij opkweek in afzonderlijke pluggen.',
    tag: 'Zaaien en opkweken', singleHeroAction: true,
    answer: { title: 'Wanneer zaailingen verspenen?', text: 'Bij veel voorgezaaide groenten is het verschijnen van de eerste echte blaadjes een bruikbaar moment om losse zaailingen een eigen potje te geven. Kijk ook naar het gewas en de ruimte. Een plant die al in een eigen plug groeit, verplaats je met de bewortelde plug als geheel.' },
    sections: [
      { kind: 'compare', title: 'Verspenen, verpotten of uitplanten?', left: { title: 'Losse zaailingen verspenen', items: ['Je haalt jonge plantjes uit een gezamenlijke zaaibak en geeft ze ieder meer ruimte.', 'Verpotten volgt wanneer een plant zijn eigen pot ontgroeit.'] }, right: { title: 'Een plug verplaatsen', items: ['Bij afzonderlijk zaaien hoeft de zaailing niet uit een gezamenlijke wortelmassa gehaald te worden.', 'Uitplanten betekent de plant naar de volgende teeltplek brengen. Dat kan na een tussenstap in een pot.'] } },
      { kind: 'prose', title: 'Hoe herken je het juiste moment?', paragraphs: ['De eerste blaadjes na het kiemen zijn kiemblaadjes. Daarna verschijnen echte bladeren met de vorm van het gewas. Wacht bij dicht gezaaide planten niet tot ze elkaar sterk verdringen, maar verplaats ook geen kwetsbaar kiempje alleen omdat een vast aantal dagen voorbij is.', ['Voor het zaaimoment en de verdere opkweek lees je onze gidsen over ', { text: 'tomaten zaaien', href: '/tomaten-zaaien' }, ' en ', { text: 'paprika zaaien', href: '/paprika-zaaien' }, '.']] },
      { kind: 'steps', title: 'Hoe kun je plantjes verspenen?', items: ['Zet schone potjes met afvoer en passend, licht vochtig substraat klaar. Maak vooraf een plantgaatje.', 'Maak de grond rond één zaailing voorzichtig los met een verspeenpen of potlood. Til de wortels van onderaf mee.', 'Houd het plantje voorzichtig aan een blad vast. Knijp niet in de stengel en trek niet aan de wortels.', 'Laat de wortels in het gaatje zakken zonder ze dubbel te vouwen. Gebruik een plantdiepte die bij het gewas past.', 'Sluit de grond voorzichtig rond de wortels aan en geef rustig water. Laat overtollig water wegstromen.'] },
      { kind: 'prose', title: 'Welke grond gebruik je na het verspenen?', paragraphs: ['Kies een substraat dat geschikt is voor de jonge plant en de volgende groeifase. Lees de verpakking: een zaaimengsel en bemeste potgrond kunnen verschillen in structuur en voeding. Gebruik een pot met afvoer en voorkom dat het mengsel langdurig verzadigd blijft.', ['Werk je met gevulde steenwoltrays? Daar voeg je geen potgrond aan toe. Lees hoe je ', guideLink, ' kunt, inclusief bevochtigen en afstemmen van de voeding.']] },
      { kind: 'prose', title: 'Wat verandert bij een zaailing in een plug?', paragraphs: [['Bij onze ', productLink, ' heeft elke kweekplaats een eigen plug met papierwikkel. Beoordeel de wortelontwikkeling vóór het verplaatsen en ondersteun de plug; trek de plant niet aan de stengel uit de tray.'], 'Laat de papierwikkel om de plug zitten en zorg voor aansluiting met het ontvangende substraat. Ook een intacte plug vraagt een passende overgang in vocht, licht en temperatuur. Dit geeft geen garantie tegen transplantatieschok.'] },
      { kind: 'cards', title: 'Nazorg en veelgemaakte fouten', items: [{ title: 'Lang en dun', text: 'Controleer de hoeveelheid licht en de onderlinge ruimte. Een grotere pot lost een tekort aan licht niet vanzelf op.' }, { title: 'Te nat', text: 'Beoordeel het substraat vóór je giet. Controleer ook of het water uit de pot kan lopen.' }, { title: 'Meteen naar buiten', text: 'Laat binnen opgekweekte planten geleidelijk wennen aan buiten. Het juiste uitplantmoment hangt ook af van kougevoeligheid en weer.' }] },
      { kind: 'prose', title: 'Moet je alle zaailingen verspenen?', paragraphs: ['Nee. Direct gezaaide gewassen en planten die al voldoende ruimte hebben vragen een andere aanpak. Bij uitdunnen haal je overtollige plantjes weg; bij verspenen verplaats je ze. Volg voor gevoelige gewassen het zaaiadvies op de verpakking.'] },
    ],
    references: { title: 'Bronnen en verder lezen', intro: 'Algemene teeltinformatie, gecontroleerd op 5 september 2026. Het advies voor jouw ras en substraat blijft leidend.', links: [sources.verspenen, sources.aftercare] },
    relatedLinks: [{ href: '/paper-plug-trays-uitgelegd', label: 'Steenwol stekpluggen gebruiken' }, { href: '/tomaten-zaaien', label: 'Tomaten zaaien en opkweken' }, { href: '/paprika-zaaien', label: 'Paprika zaaien en opkweken' }], cta,
  },
  'tomaten-zaaien': {
    title: 'Tomaten zaaien: wanneer, hoe diep en hoe verder?',
    intro: 'Tomaten opkweken begint met een zaaimoment dat past bij je kas of buitenplek. Gebruik deze gids voor het binnen voorzaaien, de kieming en de overgang naar een grotere pot of de uiteindelijke teeltplek.',
    tag: 'Zaaien en opkweken', singleHeroAction: true,
    answer: { title: 'Welke maand tomaten zaaien?', text: 'Voor een gebruikelijke Nederlandse opkweek is maart tot april een praktisch uitgangspunt. De Bolster adviseert vanaf half maart voor kasteelt en april voor buitenteelt. Zaai binnen en stem het precieze moment af op je ras, licht en de mogelijkheid om later warm uit te planten.' },
    sections: [
      { kind: 'prose', title: 'Tomaten zaaien binnen: begin met je eindbestemming', paragraphs: ['Een kas en een buitenbed geven verschillende mogelijkheden. Voor buitenteelt plant je pas uit wanneer vorst niet meer wordt verwacht; half mei is een richtpunt, geen garantie dat het lokaal warm genoeg is. Een koude kas is evenmin automatisch vorstvrij.', 'Al in januari of februari zaaien vraagt voldoende licht, warmte en ruimte voor de langere opkweek. Voor een vensterbank is later beginnen vaak beter uitvoerbaar. Schrijf eerst je geplande uitplantmoment op en controleer het rasadvies.'] },
      { kind: 'steps', title: 'Hoe zaai je zelf tomaten?', items: ['Kies zaden voor jouw teeltplek en zet schone potjes of een tray klaar. Noteer ras en zaaidatum.', 'Maak het gekozen zaaimedium gelijkmatig vochtig. Gebruik bij potjes afvoergaten.', 'Zaai in potgrond ongeveer 1 cm diep, tenzij de zaadleverancier anders adviseert. Bedek rustig en voorkom dat water de zaden verplaatst.', 'Zet het zaaisel warm weg. Controleer vocht en opkomst; laat het niet uitdrogen of in water staan.', 'Verwijder een afdekking na opkomst en geef de zaailingen veel licht. Plan de volgende stap op basis van hun ontwikkeling.'] },
      { kind: 'prose', title: 'Hoe lang duurt het voordat tomatenzaden ontkiemen?', paragraphs: ['De RHS noemt opkomst doorgaans binnen twee weken onder passende omstandigheden. Temperatuur en zaadkwaliteit maken verschil; gebruik dit niet als uiterste houdbaarheidsdatum voor ieder zaadje. Controleer bij uitblijvende opkomst eerst het rasadvies, de warmte en het vocht.', 'Een warme plek om te kiemen is niet altijd een lichte plek om verder te groeien. Lange, dunne zaailingen zijn een reden om de lichtsituatie en plantafstand opnieuw te bekijken.'] },
      { kind: 'prose', title: 'Tomaten zaaien in steenwol pluggen', paragraphs: [['Voor afzonderlijke kweekplaatsen kun je ', productLink, ' gebruiken. Een gevulde plugtray vraagt een eigen aanpak voor water en voeding; behandel steenwol niet alsof het bemeste potgrond is.'], ['Volg de uitleg voor ', guideLink, '. De aanwijzing voor zaaidiepte in potgrond is geen opdracht om in iedere plug een nieuw gat van 1 cm te maken: stem plaatsing en afdekking af op het zaad en de plug.']] },
      { kind: 'prose', title: 'Van zaailing naar pot en buitenplek', paragraphs: [['Staan de plantjes samen in een bak? Lees hoe je ', verspeenLink, ' voorzichtig aanpakt. Bij een afzonderlijke plug verplaats je de bewortelde plug als geheel.'], 'Laat de jonge planten geleidelijk wennen aan buitenomstandigheden voordat je ze definitief uitplant. Controleer zowel de wortels als de weersverwachting. Houd ook ruimte vrij voor ondersteuning en verdere groei van het gekozen tomatenras.'] },
    ],
    references: { title: 'Teeltbronnen', intro: 'Gecontroleerd op 5 september 2026. Kalenderadvies verschilt per klimaat, ras en teeltvoorziening.', links: [sources.tomatoes, sources.rhsTomatoes] },
    relatedLinks: [{ href: '/zaailingen-verspenen', label: 'Wanneer en hoe verspenen?' }, { href: '/paper-plug-trays-uitgelegd', label: 'Stekpluggen voorbereiden en gebruiken' }], cta,
  },
  'paprika-zaaien': {
    title: 'Paprika zaaien en opkweken: timing en werkwijze',
    intro: 'Paprika vraagt een warme start en een geschikte plek om verder te groeien. Hier lees je hoe je je zaaimoment kiest, waar je op let bij het zaaien en hoe je de zaailingen naar de volgende teeltfase brengt.',
    tag: 'Zaaien en opkweken', singleHeroAction: true,
    answer: { title: 'Hoe en wanneer paprika zaaien?', text: 'Zaai paprika binnen voor op een warme plek. De juiste periode hangt af van ras en teeltvoorziening: de RHS noemt half februari tot begin maart voor teelt onder glas, terwijl De Bolster voor zijn kasadvies maart–april aanhoudt. Gebruik het advies van je zaadleverancier en je eigen omstandigheden om te plannen.' },
    sections: [
      { kind: 'prose', title: 'Wat is de beste tijd om paprika te zaaien?', paragraphs: ['Vroeg zaaien is alleen bruikbaar als je de jonge planten daarna voldoende warmte, licht en ruimte kunt bieden. Bepaal eerst waar de planten uiteindelijk komen: in een kas, een pot op een beschutte plek of buiten in de grond.', 'De Bolster noemt voor Nederlandse buitenteelt binnen voorzaaien vanaf de tweede helft van april en uitplanten eind mei. Dat is een teeltadvies, geen vaste kalender voor alle rassen. Wacht met buiten zetten zolang vorst of ongeschikte kou wordt verwacht.'] },
      { kind: 'steps', title: 'Paprika zaaien: zo werk je overzichtelijk', items: ['Kies het ras en lees het zaaiadvies op de verpakking. Zet schone potjes of een geschikte tray klaar.', 'Bevochtig het zaaimedium en zorg voor afvoer van overtollig water.', 'Plaats en bedek de zaden volgens het rasadvies. Label elke rij of pot met ras en datum.', 'Zorg voor een warme kiemplek. De RHS noemt 18–21 °C voor de kieming van paprika; controleer het advies voor jouw zaad.', 'Zet opgekomen zaailingen licht en houd het medium vochtig zonder het langdurig te verzadigen. Controleer de ontwikkeling voordat je verplaatst.'] },
      { kind: 'prose', title: 'Hoe diep moet je paprika zaaien?', paragraphs: ['De RHS beschrijft voor zaaien in potjes een afdekking van ongeveer 1 cm potgrond. Gebruik een afwijkende diepte als jouw zaadverpakking die voorschrijft. Druk het medium niet hard aan. De voorbereiding van een gevulde plug verschilt van die van een pot met losse grond.', ['Kies je voor pluggen? Lees de voorbereiding voor ', guideLink, ' voordat je zaait. Noteer bij een eerste proef ook hoe je het zaad hebt geplaatst en afgedekt, zodat je de opkomst kunt vergelijken.']] },
      { kind: 'prose', title: 'Kun je de pitjes van een paprika planten?', paragraphs: ['Je kunt ermee experimenteren, maar voor een voorspelbare teelt is zaad van een bekend ras handiger. Bij een gekochte vrucht ontbreken vaak gegevens over het ras, de zaadrijpheid en de kiemkracht. Houd zo’n proef apart van de opkweek waarop je je planning baseert.'] },
      { kind: 'prose', title: 'Is paprika kweken moeilijk?', paragraphs: ['De uitdaging zit vooral in een passende, warme teeltplek en het volhouden van de verzorging. Een kas of andere beschutte voorziening geeft meer controle dan een wisselvallige buitenplek. Kies een schaal waarop je de vochtigheid en groei regelmatig kunt volgen.', ['Bij opkweek in onze ', productLink, ' blijft aandacht voor voeding en klimaat nodig. Een tray vervangt geen teeltrecept.']] },
      { kind: 'prose', title: 'Paprikazaailingen verspenen en uitplanten', paragraphs: [['Krijgen dicht gezaaide plantjes echte bladeren en hebben ze meer ruimte nodig? De gids over ', verspeenLink, ' laat zien hoe je ze voorzichtig een eigen pot geeft. Een afzonderlijk bewortelde plug verplaats je met de wikkel.'], 'Laat de planten verder groeien op een warme, lichte plek. Bereid een overgang naar buiten geleidelijk voor en beoordeel het weer. De uiteindelijke standplaats moet bij paprika warm en beschut zijn.'] },
    ],
    references: { title: 'Teeltbronnen', intro: 'Gecontroleerd op 5 september 2026. De bronnen gebruiken verschillende teeltkalenders; het rasadvies en je eigen voorzieningen bepalen de keuze.', links: [sources.peppers, sources.rhsPeppers, sources.pepperSowing] },
    relatedLinks: [{ href: '/zaailingen-verspenen', label: 'Zaailingen voorzichtig verspenen' }, { href: '/paper-plug-trays-uitgelegd', label: 'Steenwol stekpluggen gebruiken' }], cta,
  },
} satisfies Record<string, KnowledgeArticle>
